In [1]:
#Loading Packages
import tabu_search_functions
from importlib import reload
reload(tabu_search_functions)#tabu_search_functions若有更新，會重新載入
import time
import functions as functions
import numpy as np

Random Initial Solution:  ['306008001', '306016012', '307035001', '356813004', '356808001', '356564001', '307867001', '307870001', '306050011', '356019001', '306016022', '', '307851001', '307034001', '', '356387001', '356389001', '', '306525001', '356813002', '', '356813001', '307873001', '', '306000001', '356395001', '', '356425001', '356388001', '', '356461001', '306736001', '', '356822001', '356813003', '', '306737001', '307901001', '', '307857001', '306016002', '', '307942001', '307932001', '']

In [ ]:
#Tabu Search + random起始法
TimeRecord=[] #一次優化耗時紀錄
ScoreRecord=[] #一次優化分數紀錄
Schedule_optimized=[] #一次優化結果List紀錄

for i in range(10):
    print('\n\n----------------RUN', i+1 ,'----------------')
    start_time = time.time()
    
    #Tabu Search Main Function:
    TSRun = tabu_search_functions.TabuSearch(InitialMethod='random',  _NumOfNeighbor=50, _NumOfSWAP=5, _NumOfTabuList=10, _MaxIteration=100)
    
    TimeRecord.append(time.time() - start_time)
    ScoreRecord.append(TSRun[0])
    Schedule_optimized.append(TSRun[1])

----------------RUN 1 ----------------
Initial Obj. Val.:  757.0638003971337
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 822.349348
BEST MEMBER:
 ['307851001', '', '306000001', '307901001', '306525001', '356425001', '307035001', '356461001', '', '356564001', '356388001', '', '307034001', '356395001', '', '307857001', '307932001', '356019001', '307873001', '356813001', '', '307870001', '307867001', '306736001', '356813003', '306050011', '356389001', '306016012', '306737001', '', '', '306016022', '307942001', '356808001', '', '', '356813004', '', '356813002', '356387001', '356822001', '', '306016002', '306008001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 822.349348
BEST MEMBER:
 ['307851001', '', '306000001', '307901001', '306525001', '356425001', '307035001', '356461001', '', '356564001', '356388001', '', '307034001', '356395001', '', '307857001', '307932001', '356019001', '307873001', '356813001', '', '307870001', '307867001', '306736001', '356813003', '306050011', '356389001', '306016012', '306737001', '', '', '306016022', '307942001', '356808001', '', '', '356813004', '', '356813002', '356387001', '356822001', '', '306016002', '306008001', '']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 2 ----------------
Initial Obj. Val.:  728.9281705948372
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 817.107399
BEST MEMBER:
 ['307901001', '306008001', '', '356387001', '356425001', '', '306525001', '', '306737001', '307932001', '356813003', '', '307035001', '306050011', '307851001', '307942001', '356395001', '356389001', '307873001', '356813002', '', '306016002', '356813004', '', '306016012', '356564001', '306000001', '307857001', '356813001', '', '307867001', '', '356461001', '356808001', '', '356822001', '307034001', '306736001', '', '356019001', '', '307870001', '306016022', '356388001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 818.667444
BEST MEMBER:
 ['356389001', '306000001', '', '307870001', '307035001', '306008001', '356813003', '', '356387001', '307932001', '306525001', '', '306050011', '', '356395001', '306736001', '', '356425001', '307857001', '356388001', '', '306737001', '356813002', '', '306016002', '356564001', '', '356808001', '307873001', '356813001', '307851001', '306016012', '', '306016022', '356019001', '', '307901001', '', '356813004', '307942001', '356822001', '', '307034001', '307867001', '356461001']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 3 ----------------
Initial Obj. Val.:  771.6884658551324
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 822.640508
BEST MEMBER:
 ['306016022', '307867001', '356425001', '356564001', '306736001', '', '306016002', '306000001', '306016012', '307857001', '356813001', '', '306008001', '307942001', '', '306050011', '356813003', '', '307034001', '306737001', '', '307873001', '307851001', '', '307901001', '356813002', '', '356813004', '356389001', '', '356808001', '356387001', '', '307035001', '', '356019001', '306525001', '307870001', '356461001', '356822001', '356388001', '', '', '307932001', '356395001']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 822.640508
BEST MEMBER:
 ['306016022', '307867001', '356425001', '356564001', '306736001', '', '306016002', '306000001', '306016012', '307857001', '356813001', '', '306008001', '307942001', '', '306050011', '356813003', '', '307034001', '306737001', '', '307873001', '307851001', '', '307901001', '356813002', '', '356813004', '356389001', '', '356808001', '356387001', '', '307035001', '', '356019001', '306525001', '307870001', '356461001', '356822001', '356388001', '', '', '307932001', '356395001']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 4 ----------------
Initial Obj. Val.:  753.1805231805233
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 824.728050
BEST MEMBER:
 ['306737001', '356387001', '', '307867001', '356564001', '356395001', '306525001', '356822001', '', '356813004', '', '356425001', '306050011', '', '306000001', '306008001', '356808001', '', '306016022', '356813001', '', '306016012', '356813002', '', '307870001', '', '306016002', '307034001', '356019001', '356388001', '307851001', '307857001', '', '307932001', '356461001', '', '307901001', '307873001', '356389001', '307035001', '', '306736001', '', '307942001', '356813003']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 824.728050
BEST MEMBER:
 ['306737001', '356387001', '', '307867001', '356564001', '356395001', '306525001', '356822001', '', '356813004', '', '356425001', '306050011', '', '306000001', '306008001', '356808001', '', '306016022', '356813001', '', '306016012', '356813002', '', '307870001', '', '306016002', '307034001', '356019001', '356388001', '307851001', '307857001', '', '307932001', '356461001', '', '307901001', '307873001', '356389001', '307035001', '', '306736001', '', '307942001', '356813003']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 5 ----------------
Initial Obj. Val.:  748.6132694466027
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 819.531641
BEST MEMBER:
 ['356813004', '', '306000001', '', '307870001', '356387001', '307034001', '356813001', '', '306050011', '356461001', '', '307851001', '306737001', '', '356808001', '356389001', '', '307901001', '356813002', '307035001', '306016012', '306736001', '', '306525001', '307873001', '', '307867001', '', '356395001', '306016002', '356388001', '306008001', '356564001', '356019001', '356425001', '356813003', '307932001', '', '356822001', '', '307942001', '', '307857001', '306016022']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 826.860485
BEST MEMBER:
 ['356564001', '356395001', '', '307901001', '356388001', '', '356808001', '306000001', '', '356813003', '306016012', '', '306050011', '307942001', '', '307851001', '', '356425001', '307867001', '356389001', '', '307034001', '306525001', '', '306736001', '356461001', '356813004', '307035001', '307873001', '', '306016002', '307857001', '', '307870001', '356813002', '306008001', '356387001', '356822001', '', '306016022', '', '356813001', '306737001', '307932001', '356019001']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 6 ----------------
Initial Obj. Val.:  772.7877061210395
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 811.305577
BEST MEMBER:
 ['307870001', '307932001', '', '307851001', '356822001', '', '306050011', '306008001', '306000001', '356387001', '307873001', '', '356389001', '356425001', '356395001', '306525001', '356388001', '', '356564001', '356813001', '356808001', '356813004', '356813003', '', '306737001', '306736001', '306016022', '307901001', '306016012', '', '307942001', '356813002', '', '306016002', '', '307035001', '', '307034001', '356461001', '307867001', '', '', '307857001', '356019001', '']

In [31]:
# 展示結果

for i in range(len(ScoreRecord)):
    print('第',i,'輪分數(0~1000分): %.2f' %ScoreRecord[i], '  第',i,'輪耗時（秒）: %.2f' %TimeRecord[i])
print('此10輪最佳解為：\n')
functions.ListToSchedule(Schedule_optimized[np.argmax(ScoreRecord)])

第 0 輪分數(0~1000分): 830.51   第 0 輪耗時（秒）: 23.36
第 1 輪分數(0~1000分): 819.90   第 1 輪耗時（秒）: 22.44
第 2 輪分數(0~1000分): 820.01   第 2 輪耗時（秒）: 22.82
第 3 輪分數(0~1000分): 817.26   第 3 輪耗時（秒）: 23.15
第 4 輪分數(0~1000分): 820.40   第 4 輪耗時（秒）: 23.91
第 5 輪分數(0~1000分): 819.64   第 5 輪耗時（秒）: 24.11
第 6 輪分數(0~1000分): 824.40   第 6 輪耗時（秒）: 23.09
第 7 輪分數(0~1000分): 825.36   第 7 輪耗時（秒）: 23.31
第 8 輪分數(0~1000分): 824.35   第 8 輪耗時（秒）: 22.24
第 9 輪分數(0~1000分): 827.93   第 9 輪耗時（秒）: 25.97
此10輪最佳解為：

             Mon                              Tue                         Wed  \
           Room1      Room2      Room3      Room1      Room2 Room3      Room1
0  上午  306736001  307932001  356813001  306008001  356813003        307901001
1  下午  306050011  356808001             307857001  307873001        307851001
2  晚上  356389001  306525001             307867001  306000001        356813004

                               Thu                              Fri  \
       Room2      Room3      Room1      Room2      Room3      Room1
0  307942001             356019001  306737001  356395001  356387001
1  356813002             306016022             356461001  307034001
2             356425001  307035001  306016012             356564001


       Room2      Room3
0  356822001
1  306016002  356388001
2  307870001