In [5]:
#Loading Packages
import tabu_search_functions
from importlib import reload
reload(tabu_search_functions)#tabu_search_functions若有更新，會重新載入
import time
import functions as functions
import numpy as np

In [6]:
#Tabu Search + 嗡嗡起始法
TimeRecord=[] #一次優化耗時紀錄
ScoreRecord=[] #一次優化分數紀錄
Schedule_optimized=[] #一次優化結果List紀錄

for i in range(10):
    print('\n\n----------------RUN', i+1 ,'----------------')
    start_time = time.time()
    
    #Tabu Search Main Function:
    TSRun = tabu_search_functions.TabuSearch(InitialMethod='random',  _NumOfNeighbor=50, _NumOfSWAP=5, _NumOfTabuList=10, _MaxIteration=100)
    
    TimeRecord.append(time.time() - start_time)
    ScoreRecord.append(TSRun[0])
    Schedule_optimized.append(TSRun[1])

----------------RUN 1 ----------------
Initial Obj. Val.:  758.6456444789778
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 827.084952
BEST MEMBER:
 ['306736001', '356387001', '', '356389001', '', '307942001', '307932001', '356813003', '356461001', '306016022', '356388001', '', '', '306525001', '307857001', '307867001', '307870001', '', '307035001', '356019001', '', '307901001', '356808001', '356395001', '356813004', '306016002', '', '306016012', '307034001', '356822001', '306737001', '356813002', '', '356564001', '', '356425001', '', '356813001', '306000001', '306050011', '307851001', '', '307873001', '306008001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 828.196063
BEST MEMBER:
 ['', '307932001', '356813001', '306008001', '356813003', '', '307901001', '307942001', '306736001', '306737001', '356019001', '356395001', '356387001', '356822001', '', '306050011', '356808001', '', '307857001', '307873001', '', '307851001', '356813002', '', '306016022', '', '356461001', '307034001', '306016002', '', '356389001', '306525001', '', '307867001', '306000001', '', '356813004', '356388001', '356425001', '307035001', '306016012', '', '356564001', '307870001', '']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 2 ----------------
Initial Obj. Val.:  764.2810584477251
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 819.542865
BEST MEMBER:
 ['307932001', '356822001', '356813001', '306737001', '356019001', '', '356389001', '306525001', '306000001', '306008001', '356813003', '356425001', '356564001', '', '306016022', '306050011', '', '307857001', '306016012', '', '356388001', '356813004', '', '307942001', '', '356808001', '356813002', '307851001', '', '307035001', '306016002', '', '307870001', '307873001', '307901001', '', '307034001', '356395001', '', '306736001', '307867001', '', '356387001', '356461001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 819.902659
BEST MEMBER:
 ['306737001', '307867001', '307942001', '306016002', '307870001', '306000001', '307034001', '307857001', '356395001', '306525001', '356813002', '', '356813004', '307901001', '', '356387001', '356388001', '306050011', '306736001', '356808001', '', '306016012', '356813003', '', '307035001', '356461001', '', '356822001', '356813001', '', '356389001', '356425001', '', '', '356019001', '', '306008001', '356564001', '', '307873001', '307851001', '', '306016022', '307932001', '']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 3 ----------------
Initial Obj. Val.:  750.6902356902357
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 820.014245
BEST MEMBER:
 ['356808001', '307034001', '306000001', '306050011', '307901001', '', '', '306016022', '356019001', '', '306008001', '307035001', '307857001', '307867001', '', '307851001', '356813002', '306016012', '356813004', '356388001', '356425001', '307932001', '307870001', '', '306737001', '307942001', '', '356389001', '307873001', '', '', '356395001', '306525001', '356387001', '356564001', '', '', '356822001', '356813001', '306736001', '356813003', '', '306016002', '356461001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 820.014245
BEST MEMBER:
 ['356808001', '307034001', '306000001', '306050011', '307901001', '', '', '306016022', '356019001', '', '306008001', '307035001', '307857001', '307867001', '', '307851001', '356813002', '306016012', '356813004', '356388001', '356425001', '307932001', '307870001', '', '306737001', '307942001', '', '356389001', '307873001', '', '', '356395001', '306525001', '356387001', '356564001', '', '', '356822001', '356813001', '306736001', '356813003', '', '306016002', '356461001', '']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 4 ----------------
Initial Obj. Val.:  738.2310282310282
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 816.411551
BEST MEMBER:
 ['', '306737001', '356813001', '306525001', '307034001', '', '306050011', '356388001', '', '356564001', '356813004', '356395001', '307870001', '356813003', '356019001', '', '307873001', '307942001', '307851001', '307932001', '', '307857001', '307901001', '356387001', '306008001', '306000001', '', '306736001', '356425001', '', '307867001', '', '356389001', '306016022', '356808001', '', '306016012', '', '356461001', '306016002', '356813002', '', '307035001', '356822001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 817.264526
BEST MEMBER:
 ['307870001', '356822001', '', '307857001', '356387001', '', '356564001', '356395001', '', '307867001', '307901001', '', '307873001', '307034001', '', '', '307942001', '306016022', '356813004', '356425001', '', '306016012', '356813003', '356019001', '306008001', '356461001', '', '306050011', '306525001', '307932001', '307851001', '306736001', '', '307035001', '', '356388001', '356389001', '356813001', '356808001', '', '356813002', '306000001', '306737001', '', '306016002']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 5 ----------------
Initial Obj. Val.:  756.7277475610808
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 820.395839
BEST MEMBER:
 ['', '356813003', '356813002', '306525001', '307857001', '', '306736001', '', '356425001', '307932001', '306016012', '356389001', '307851001', '', '306000001', '356808001', '356461001', '', '307901001', '', '307867001', '307035001', '306050011', '', '306016002', '356564001', '', '307870001', '356388001', '356387001', '', '356019001', '356395001', '306008001', '306016022', '', '307034001', '307942001', '', '307873001', '356822001', '356813001', '356813004', '306737001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 820.395839
BEST MEMBER:
 ['', '356813003', '356813002', '306525001', '307857001', '', '306736001', '', '356425001', '307932001', '306016012', '356389001', '307851001', '', '306000001', '356808001', '356461001', '', '307901001', '', '307867001', '307035001', '306050011', '', '306016002', '356564001', '', '307870001', '356388001', '356387001', '', '356019001', '356395001', '306008001', '306016022', '', '307034001', '307942001', '', '307873001', '356822001', '356813001', '356813004', '306737001', '']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 6 ----------------
Initial Obj. Val.:  747.1766813433479
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 815.468790
BEST MEMBER:
 ['356813003', '', '356395001', '356808001', '', '306008001', '306016002', '', '356813001', '307867001', '307035001', '', '356019001', '356461001', '306736001', '307851001', '307870001', '356822001', '306050011', '356425001', '', '356813004', '307942001', '', '306737001', '356813002', '', '307932001', '307873001', '306525001', '', '356387001', '306000001', '', '307034001', '307901001', '306016022', '356388001', '', '306016012', '356564001', '', '356389001', '307857001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 819.644522
BEST MEMBER:
 ['307901001', '', '', '307034001', '356813003', '306525001', '356813004', '', '306016022', '356564001', '356019001', '', '307857001', '', '356389001', '307851001', '', '356813002', '307867001', '', '307870001', '356387001', '356461001', '', '306050011', '356822001', '', '356808001', '306737001', '', '307035001', '307873001', '', '306016012', '356388001', '306000001', '306016002', '307942001', '', '306736001', '306008001', '356425001', '307932001', '356395001', '356813001']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 7 ----------------
Initial Obj. Val.:  764.4599844599845
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 817.051282
BEST MEMBER:
 ['307942001', '306008001', '', '306050011', '306016012', '', '356813004', '', '356461001', '306016002', '307873001', '', '306736001', '', '356822001', '306016022', '', '306525001', '306737001', '356019001', '307901001', '356389001', '356395001', '356564001', '307851001', '356813003', '', '307034001', '356813001', '356808001', '307857001', '356388001', '', '', '356387001', '307035001', '307870001', '', '306000001', '307867001', '356813002', '', '', '307932001', '356425001']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 824.402573
BEST MEMBER:
 ['307035001', '356395001', '', '306050011', '356461001', '', '306525001', '', '306000001', '356389001', '356813001', '356425001', '356813004', '306016022', '', '306016002', '356387001', '', '307034001', '307870001', '', '307901001', '307942001', '307932001', '356564001', '', '306008001', '356808001', '', '307873001', '306736001', '356019001', '', '306737001', '356388001', '', '307851001', '', '307857001', '307867001', '356813003', '', '306016012', '356813002', '356822001']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 8 ----------------
Initial Obj. Val.:  741.2950012950013
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 816.815592
BEST MEMBER:
 ['356389001', '356461001', '', '307942001', '', '356813003', '356822001', '', '356395001', '307867001', '306016022', '356425001', '307034001', '306008001', '', '356387001', '306016002', '', '307851001', '306737001', '307870001', '306050011', '306525001', '', '306016012', '307873001', '306000001', '307857001', '306736001', '', '307932001', '356808001', '', '', '356813002', '356813004', '', '356388001', '356019001', '307035001', '', '356813001', '356564001', '307901001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 825.356557
BEST MEMBER:
 ['356564001', '306008001', '', '356822001', '307942001', '', '306016012', '356813004', '356425001', '306525001', '', '306737001', '307870001', '', '356389001', '307857001', '307901001', '', '307034001', '307867001', '356388001', '356808001', '307851001', '', '306016022', '356813003', '356813001', '', '307873001', '356387001', '306736001', '356019001', '', '', '307932001', '306000001', '306050011', '356813002', '', '307035001', '356395001', '', '306016002', '356461001', '']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 9 ----------------
Initial Obj. Val.:  747.0314253647588
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 816.254425
BEST MEMBER:
 ['306016012', '356813002', '', '307034001', '307851001', '', '356389001', '', '306008001', '356813004', '356564001', '', '306016002', '356387001', '', '307932001', '307873001', '356019001', '356808001', '306000001', '', '306736001', '306050011', '', '306525001', '307901001', '356425001', '307035001', '', '356813001', '307867001', '307942001', '356461001', '306737001', '356388001', '', '306016022', '356813003', '', '356395001', '', '356822001', '', '307870001', '307857001']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 824.346456
BEST MEMBER:
 ['307867001', '307942001', '', '356389001', '306736001', '306016012', '356387001', '307857001', '', '356019001', '', '356425001', '356813004', '356822001', '', '307035001', '', '356395001', '307851001', '356461001', '356813003', '306525001', '356564001', '', '306016002', '306008001', '356813002', '', '306000001', '306016022', '307901001', '306737001', '', '307873001', '307932001', '', '307034001', '307870001', '', '306050011', '356388001', '', '356808001', '', '356813001']


TERMINATING - REACHED MAXIMUM STEPS


----------------RUN 10 ----------------
Initial Obj. Val.:  758.1649831649831
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']


TABU SEARCH:
CURRENT STEPS: 50
BEST SCORE: 827.927350
BEST MEMBER:
 ['307035001', '307942001', '', '306736001', '356461001', '356813001', '356808001', '356388001', '', '356387001', '356822001', '356389001', '306525001', '306016012', '', '307034001', '307870001', '', '307901001', '356813002', '', '356813004', '356813003', '306000001', '307932001', '', '307857001', '306016002', '356019001', '356425001', '307867001', '', '356395001', '306737001', '', '', '306016022', '307851001', '', '306008001', '307873001', '', '306050011', '356564001', '']


TABU SEARCH:
CURRENT STEPS: 100
BEST SCORE: 827.927350
BEST MEMBER:
 ['307035001', '307942001', '', '306736001', '356461001', '356813001', '356808001', '356388001', '', '356387001', '356822001', '356389001', '306525001', '306016012', '', '307034001', '307870001', '', '307901001', '356813002', '', '356813004', '356813003', '306000001', '307932001', '', '307857001', '306016002', '356019001', '356425001', '307867001', '', '356395001', '306737001', '', '', '306016022', '307851001', '', '306008001', '307873001', '', '306050011', '356564001', '']


TERMINATING - REACHED MAXIMUM STEPS

In [31]:

for i in range(len(ScoreRecord)):
    print('第',i,'輪分數(0~1000分): %.2f' %ScoreRecord[i], '  第',i,'輪耗時（秒）: %.2f' %TimeRecord[i])
print('此10輪最佳解為：\n')
functions.ListToSchedule(Schedule_optimized[np.argmax(ScoreRecord)])

第 0 輪分數(0~1000分): 830.51   第 0 輪耗時（秒）: 23.36
第 1 輪分數(0~1000分): 819.90   第 1 輪耗時（秒）: 22.44
第 2 輪分數(0~1000分): 820.01   第 2 輪耗時（秒）: 22.82
第 3 輪分數(0~1000分): 817.26   第 3 輪耗時（秒）: 23.15
第 4 輪分數(0~1000分): 820.40   第 4 輪耗時（秒）: 23.91
第 5 輪分數(0~1000分): 819.64   第 5 輪耗時（秒）: 24.11
第 6 輪分數(0~1000分): 824.40   第 6 輪耗時（秒）: 23.09
第 7 輪分數(0~1000分): 825.36   第 7 輪耗時（秒）: 23.31
第 8 輪分數(0~1000分): 824.35   第 8 輪耗時（秒）: 22.24
第 9 輪分數(0~1000分): 827.93   第 9 輪耗時（秒）: 25.97
此10輪最佳解為：

             Mon                              Tue                         Wed  \
           Room1      Room2      Room3      Room1      Room2 Room3      Room1
0  上午  306736001  307932001  356813001  306008001  356813003        307901001
1  下午  306050011  356808001             307857001  307873001        307851001
2  晚上  356389001  306525001             307867001  306000001        356813004

                               Thu                              Fri  \
       Room2      Room3      Room1      Room2      Room3      Room1
0  307942001             356019001  306737001  356395001  356387001
1  356813002             306016022             356461001  307034001
2             356425001  307035001  306016012             356564001


       Room2      Room3
0  356822001
1  306016002  356388001
2  307870001

In [40]:
ScoreRecordGA=[709.6644219977554,
 720.2817059483726, 
718.7306397306398, 
713.8709315375983, 
703.615039281706, 
714.2570145903479, 
710.1245791245792, 
709.9483726150393,
 724.493827160494, 
701.9180695847363]
TimeRecordGA=[19.643171787261963, 
10.451020956039429,
 28.324418544769287, 
17.759281158447266,
 16.355666160583496, 
16.16285014152527, 
17.549039602279663, 
15.833794832229614, 
17.748189687728882, 
17.217735290527344]


for i in range(len(ScoreRecord)):
    print('第',i,'輪分數(0~1000分): %.2f' %ScoreRecordGA[i], '  第',i,'輪耗時（秒）: %.2f' %TimeRecordGA[i])
print('此10輪最佳解為：\n')
functions.ListToSchedule(Schedule_optimized[np.argmax(ScoreRecord)])
print( Schedule_optimized[np.argmax(ScoreRecord)] )

第 0 輪分數(0~1000分): 709.66   第 0 輪耗時（秒）: 19.64
第 1 輪分數(0~1000分): 720.28   第 1 輪耗時（秒）: 10.45
第 2 輪分數(0~1000分): 718.73   第 2 輪耗時（秒）: 28.32
第 3 輪分數(0~1000分): 713.87   第 3 輪耗時（秒）: 17.76
第 4 輪分數(0~1000分): 703.62   第 4 輪耗時（秒）: 16.36
第 5 輪分數(0~1000分): 714.26   第 5 輪耗時（秒）: 16.16
第 6 輪分數(0~1000分): 710.12   第 6 輪耗時（秒）: 17.55
第 7 輪分數(0~1000分): 709.95   第 7 輪耗時（秒）: 15.83
第 8 輪分數(0~1000分): 724.49   第 8 輪耗時（秒）: 17.75
第 9 輪分數(0~1000分): 701.92   第 9 輪耗時（秒）: 17.22
此10輪最佳解為：

['306736001', '307932001', '356813001', '306008001', '356813003', '', '307901001', '307942001', '', '356019001', '306737001', '356395001', '356387001', '356822001', '', '306050011', '356808001', '', '307857001', '307873001', '', '307851001', '356813002', '', '306016022', '', '356461001', '307034001', '306016002', '356388001', '356389001', '306525001', '', '307867001', '306000001', '', '356813004', '', '356425001', '307035001', '306016012', '', '356564001', '307870001', '']

In [35]:

s =  ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', ''] 
functions.ListToSchedule(s)

             Mon                              Tue                        \
           Room1      Room2      Room3      Room1      Room2      Room3
0  上午  306000001             306008001                        306016002
1  下午  306016022  307857001  306050011  356387001  356388001  307851001
2  晚上  307932001             356822001             356389001  356019001

         Wed                         Thu                              Fri  \
       Room1 Room2      Room3      Room1      Room2      Room3      Room1
0  356425001        306016012  307873001             307867001  307942001
1  306525001        307035001  306736001  356395001  307034001  356461001
2  356564001        307901001  356813001             356808001


  Room2      Room3
0        307870001
1        306737001
2