In [1]:
import tabu_search_functions
import time
import functions as functions

In [3]:
#Tabu Search
ScoreRecord=[]
Schedule_optimized=[]
TimeRecord=[]
for i in range(2):
    start_time = time.time()
    TSRun = tabu_search_functions.TabuSearch()
    print(TSRun)
    ScoreRecord.append(TSRun[0])
    Schedule_optimized.append(TSRun[1])
    TimeRecord.append(time.time() - start_time)

Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']
Initial Obj. Val.:  758.5297418630753
TABU SEARCH:
CURRENT STEPS: 10
BEST SCORE: 772.682379
BEST MEMBER: ['307932001', '', '356019001', '', '306016012', '356564001', '307851001', '307870001', '306050011', '307867001', '356813002', '', '356387001', '', '307034001', '307035001', '306016022', '356425001', '306008001', '356389001', '', '306525001', '307873001', '', '307901001', '356395001', '', '', '356388001', '306000001', '', '306736001', '356461001', '307857001', '356813001', '', '306737001', '306016002', '', '356822001', '307942001', '', '356808001', '356813003', '356813004']


TABU SEARCH:
CURRENT STEPS: 20
BEST SCORE: 772.682379
BEST MEMBER: ['307932001', '', '356019001', '', '306016012', '356564001', '307851001', '307870001', '306050011', '307867001', '356813002', '', '356387001', '', '307034001', '307035001', '306016022', '356425001', '306008001', '356389001', '', '306525001', '307873001', '', '307901001', '356395001', '', '', '356388001', '306000001', '', '306736001', '356461001', '307857001', '356813001', '', '306737001', '306016002', '', '356822001', '307942001', '', '356808001', '356813003', '356813004']


TABU SEARCH:
CURRENT STEPS: 30
BEST SCORE: 774.096521
BEST MEMBER: ['307901001', '356822001', '356813001', '', '356461001', '356019001', '307035001', '307851001', '', '307870001', '356813004', '356395001', '307873001', '', '356389001', '', '306525001', '306000001', '306050011', '306008001', '', '306016022', '306736001', '', '356387001', '306016002', '307034001', '306016012', '356813003', '', '', '356388001', '356564001', '307867001', '', '307932001', '306737001', '307942001', '', '356808001', '', '356425001', '307857001', '356813002', '']


TERMINATING - REACHED MAXIMUM STEPS
(774.0965207631875, ['307901001', '356822001', '356813001', '', '356461001', '356019001', '307035001', '307851001', '', '307870001', '356813004', '356395001', '307873001', '', '356389001', '', '306525001', '306000001', '306050011', '306008001', '', '306016022', '306736001', '', '356387001', '306016002', '307034001', '306016012', '356813003', '', '', '356388001', '356564001', '307867001', '', '307932001', '306737001', '307942001', '', '356808001', '', '356425001', '307857001', '356813002', ''], 6.513236999511719)
Initial Solution:
 ['306000001', '', '306008001', '', '', '306016002', '356425001', '', '306016012', '307873001', '', '307867001', '307942001', '', '307870001', '306016022', '307857001', '306050011', '356387001', '356388001', '307851001', '306525001', '', '307035001', '306736001', '356395001', '307034001', '356461001', '', '306737001', '307932001', '', '356822001', '', '356389001', '356019001', '356564001', '', '307901001', '356813001', '', '356808001', '', '', '']
Initial Obj. Val.:  757.351290684624
TABU SEARCH:
CURRENT STEPS: 10
BEST SCORE: 767.991021
BEST MEMBER: ['356813004', '356808001', '356425001', '307851001', '356564001', '', '306008001', '306016012', '306050011', '356387001', '306000001', '', '356019001', '356389001', '', '307857001', '356813002', '', '307035001', '306736001', '', '307901001', '307034001', '', '356813001', '307870001', '', '', '356388001', '307942001', '306525001', '356395001', '', '306737001', '306016022', '', '356822001', '356813003', '', '307932001', '306016002', '356461001', '307873001', '307867001', '']


TABU SEARCH:
CURRENT STEPS: 20
BEST SCORE: 778.350168
BEST MEMBER: ['306736001', '307870001', '', '307034001', '306016012', '', '356822001', '307901001', '', '306737001', '306016002', '', '356564001', '306016022', '', '307857001', '356389001', '', '307035001', '356813004', '306000001', '356387001', '', '356813002', '356461001', '307942001', '356813001', '307851001', '307932001', '', '', '356808001', '356019001', '306525001', '', '356425001', '307867001', '356388001', '', '306050011', '356395001', '306008001', '307873001', '', '356813003']


TABU SEARCH:
CURRENT STEPS: 30
BEST SCORE: 781.840629
BEST MEMBER: ['306736001', '307870001', '', '307034001', '356813004', '', '356822001', '307901001', '', '306737001', '306016002', '', '306008001', '306016022', '', '307857001', '356389001', '', '307035001', '356808001', '306000001', '356387001', '', '356813002', '', '307942001', '356813001', '307851001', '307932001', '356461001', '', '306016012', '356019001', '306525001', '', '356425001', '307867001', '356388001', '', '306050011', '356395001', '', '307873001', '356564001', '356813003']


TERMINATING - REACHED MAXIMUM STEPS
(781.8406285072953, ['306736001', '307870001', '', '307034001', '356813004', '', '356822001', '307901001', '', '306737001', '306016002', '', '306008001', '306016022', '', '307857001', '356389001', '', '307035001', '356808001', '306000001', '356387001', '', '356813002', '', '307942001', '356813001', '307851001', '307932001', '356461001', '', '306016012', '356019001', '306525001', '', '356425001', '307867001', '356388001', '', '306050011', '356395001', '', '307873001', '356564001', '356813003'], 6.709297180175781)

In [8]:
display(
    ScoreRecord,
    TimeRecord,
    functions.ListToSchedule(Schedule_optimized[0])
)

[774.0965207631875, 781.8406285072953]

[6.618775129318237, 6.776566743850708]

             Mon                              Tue                        \
           Room1      Room2      Room3      Room1      Room2      Room3
0  上午  307901001  356822001  356813001             356461001  356019001
1  下午             306525001  306000001  306050011  306008001
2  晚上             356388001  356564001  307867001             307932001

         Wed                         Thu                              Fri  \
       Room1      Room2 Room3      Room1      Room2      Room3      Room1
0  307035001  307851001        307870001  356813004  356395001  307873001
1  306016022  306736001        356387001  306016002  307034001  306016012
2  306737001  307942001        356808001             356425001  307857001


       Room2      Room3
0             356389001
1  356813003
2  356813002